export interface IIHomeHeaderComponentLess {
  'ant-btn': string;
  'ant-form-item': string;
  'ant-input': string;
  'ant-layout': string;
  'ant-layout-has-sider': string;
  'ant-radio-group': string;
  'ant-spin': string;
  'ant-spin-container': string;
  'ant-spin-nested-loading': string;
  'ant-spin-spinning': string;
  'ant-tree': string;
  'ant-tree-node-content-wrapper': string;
  antBtn: string;
  antFormItem: string;
  antInput: string;
  antLayout: string;
  antLayoutHasSider: string;
  antRadioGroup: string;
  antSpin: string;
  antSpinContainer: string;
  antSpinNestedLoading: string;
  antSpinSpinning: string;
  antTree: string;
  antTreeNodeContentWrapper: string;
  container: string;
  'custom-layout': string;
  'custom-layout-spin': string;
  customLayout: string;
  customLayoutSpin: string;
  'fold-icon': string;
  foldIcon: string;
  h40: string;
  header: string;
  'header-left': string;
  'header-logo': string;
  'header-right': string;
  headerLeft: string;
  headerLogo: string;
  headerRight: string;
  label: string;
  'login-form': string;
  loginForm: string;
  'logo-container': string;
  logoContainer: string;
  main: string;
  'other-search-button-item': string;
  otherSearchButtonItem: string;
  'push-search-item': string;
  pushSearchItem: string;
  root: string;
  setting: string;
  trigger: string;
}

export const locals: IIHomeHeaderComponentLess;
export default locals;
