import { prefixActionTypes } from '~/framework/util/common';

export const TYPES = {
  SET_FORM_INFO: 'SET_FORM_INFO',
  SET_FLOWNODE_SETTING_FIELD: 'SET_FLOWNODE_SETTING_FIELD',
  SET_CURRENT_SELECT_ITEM: 'SET_CURRENT_SELECT_ITEM',
  SET_CURRENT_PARAMS: 'SET_CURRENT_PARAMS',
  SET_APPROVER_INPUT: 'SET_APPROVER_INPUT',
  SET_TEMPLATE_NAME: 'SET_TEMPLATE_NAME',
  INIT_TEMPLATE_FORM: 'INIT_TEMPLATE_FORM'
};

prefixActionTypes('ADD_TEMPLATE')(TYPES);
