export interface IRoleManageComponentLess {
  'ant-btn': string;
  'ant-form-item': string;
  'ant-input': string;
  'ant-layout': string;
  'ant-layout-has-sider': string;
  'ant-radio-group': string;
  'ant-spin': string;
  'ant-spin-container': string;
  'ant-spin-nested-loading': string;
  'ant-spin-spinning': string;
  'ant-tree': string;
  'ant-tree-node-content-wrapper': string;
  antBtn: string;
  antFormItem: string;
  antInput: string;
  antLayout: string;
  antLayoutHasSider: string;
  antRadioGroup: string;
  antSpin: string;
  antSpinContainer: string;
  antSpinNestedLoading: string;
  antSpinSpinning: string;
  antTree: string;
  antTreeNodeContentWrapper: string;
  container: string;
  'custom-layout': string;
  'custom-layout-spin': string;
  customLayout: string;
  customLayoutSpin: string;
  'form-item': string;
  formItem: string;
  h40: string;
  label: string;
  layout: string;
  'login-form': string;
  loginForm: string;
  'other-search-button-item': string;
  otherSearchButtonItem: string;
  'push-search-item': string;
  pushSearchItem: string;
  'role-table': string;
  roleTable: string;
  root: string;
  side: string;
}

export const locals: IRoleManageComponentLess;
export default locals;
