export interface ILoginComponentLess {
  'ant-btn': string;
  'ant-form-item': string;
  'ant-input': string;
  'ant-layout': string;
  'ant-layout-has-sider': string;
  'ant-radio-group': string;
  'ant-spin': string;
  'ant-spin-container': string;
  'ant-spin-nested-loading': string;
  'ant-spin-spinning': string;
  'ant-tree': string;
  'ant-tree-node-content-wrapper': string;
  antBtn: string;
  antFormItem: string;
  antInput: string;
  antLayout: string;
  antLayoutHasSider: string;
  antRadioGroup: string;
  antSpin: string;
  antSpinContainer: string;
  antSpinNestedLoading: string;
  antSpinSpinning: string;
  antTree: string;
  antTreeNodeContentWrapper: string;
  'custom-layout': string;
  'custom-layout-spin': string;
  customLayout: string;
  customLayoutSpin: string;
  'form-item': string;
  formFlexItem: string;
  formItem: string;
  h40: string;
  label: string;
  left: string;
  leftCover: string;
  'login-form': string;
  loginBox: string;
  loginBtn: string;
  loginForm: string;
  main: string;
  'other-search-button-item': string;
  otherSearchButtonItem: string;
  'push-search-item': string;
  pushSearchItem: string;
  right: string;
  root: string;
  siteTitleBox: string;
  stage: string;
  vcodeBox: string;
  vcodeInput: string;
  welcome: string;
}

export const locals: ILoginComponentLess;
export default locals;
