export interface INotFoundComponentLess {
  'ant-btn': string;
  'ant-form-item': string;
  'ant-input': string;
  'ant-layout': string;
  'ant-layout-has-sider': string;
  'ant-select': string;
  'ant-spin': string;
  'ant-spin-container': string;
  'ant-spin-nested-loading': string;
  'ant-spin-spinning': string;
  antBtn: string;
  antFormItem: string;
  antInput: string;
  antLayout: string;
  antLayoutHasSider: string;
  antSelect: string;
  antSpin: string;
  antSpinContainer: string;
  antSpinNestedLoading: string;
  antSpinSpinning: string;
  button: string;
  'custom-layout': string;
  'custom-layout-spin': string;
  customLayout: string;
  customLayoutSpin: string;
  h40: string;
  label: string;
  'login-form': string;
  loginForm: string;
  main: string;
  'not-found-view': string;
  notFoundView: string;
  'other-search-button-item': string;
  otherSearchButtonItem: string;
  'push-search-item': string;
  pushSearchItem: string;
  root: string;
}

export const locals: INotFoundComponentLess;
export default locals;
