export interface IAddOrganizationComponentLess {
  'ant-btn': string;
  'ant-form-item': string;
  'ant-input': string;
  'ant-layout': string;
  'ant-layout-has-sider': string;
  'ant-radio-group': string;
  'ant-select': string;
  'ant-spin': string;
  'ant-spin-container': string;
  'ant-spin-nested-loading': string;
  'ant-spin-spinning': string;
  'ant-tree': string;
  'ant-tree-node-content-wrapper': string;
  antBtn: string;
  antFormItem: string;
  antInput: string;
  antLayout: string;
  antLayoutHasSider: string;
  antRadioGroup: string;
  antSelect: string;
  antSpin: string;
  antSpinContainer: string;
  antSpinNestedLoading: string;
  antSpinSpinning: string;
  antTree: string;
  antTreeNodeContentWrapper: string;
  'base-info': string;
  baseInfo: string;
  'custom-layout': string;
  'custom-layout-spin': string;
  customLayout: string;
  customLayoutSpin: string;
  h40: string;
  header: string;
  label: string;
  'label-value': string;
  labelValue: string;
  'line-container': string;
  lineContainer: string;
  'login-form': string;
  loginForm: string;
  'organization-main': string;
  organizationMain: string;
  'other-search-button-item': string;
  otherSearchButtonItem: string;
  'push-search-item': string;
  pushSearchItem: string;
  require: string;
  root: string;
  'submit-button': string;
  submitButton: string;
  'upload-images': string;
  uploadImages: string;
}

export const locals: IAddOrganizationComponentLess;
export default locals;
